apiVersion: v2
name: redis-replication
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
type: application
engine: gotpl
maintainers:
  - name: Tony
sources:
  - https://github.com/tonyfieit75/z-redis-operator
version: 0.16.2
appVersion: "0.16.2"
home: https://github.com/tonyfieit75/z-redis-operator
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
- redis-exporter
icon: https://github.com/tonyfieit75/z-redis-operator/raw/master/static/redis-operator-logo.svg
